/*
 * Ultrasonic_private.h
 *
 * Created: 10/30/2023 10:27:43 AM
 *  Author: Ziad
 */ 


#ifndef ULTRASONIC_PRIVATE_H_
#define ULTRASONIC_PRIVATE_H_


/*
 • Description : 1-This is the call back function called by the ICU driver.
               : 2-This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 • Inputs      : None
 • Return      : None
 */

void Ultrasonic_edgeProcessing(void);


#endif /* ULTRASONIC_PRIVATE_H_ */