/*
 * TIMER0_config.h
 *
 * Created: 10/26/2023 2:20:06 PM
 *  Author: zashr
 */ 


#ifndef TIMER0_CONFIG_H_
#define TIMER0_CONFIG_H_

/*
	Choose one of the following :
	
	TIMER0_PRESCALER_1
	TIMER0_PRESCALER_8
	TIMER0_PRESCALER_64
	TIMER0_PRESCALER_256
	TIMER0_PRESCALER_1024
	TIMER0_EXT_CLK_FALL_EDGE
	TIMER0_EXT_CLK_RAIS_EDGE
*/

#define TIMER0_PRESCALER TIMER0_PRESCALER_1024

/*
	Choose one of the following :
	
	TIMER0_MODE_NORMAL
	TIMER0_MODE_CTC
	TIMER0_MODE_FAST_PWM
	TIMER0_MODE_PHASE_CORRECT_PWM
*/

#define TIMER0_MODE

/*
	Choose one of the following :
	
	TIMER0_OC0_DISCONNECTED
	TIMER0_OC0_SET
	TIMER0_OC0_CLR
	TIMER0_OC0_TOGGLE
*/

#define TIMER0_OC0_MODE


#endif /* TIMER0_CONFIG_H_ */